# Generated by Django 3.0.3 on 2020-02-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('acct_type', models.CharField(default='', max_length=20)),
                ('owner', models.CharField(default='', max_length=400)),
                ('dt_opened', models.DateTimeField(blank=True, null=True)),
                ('interest_rt', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(default='', max_length=100)),
                ('amount', models.CharField(default='', max_length=100)),
                ('hello', models.TextField(default='', max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.Accounts')),
            ],
        ),
    ]
