# Generated by Django 3.0.3 on 2020-02-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('acct_type', models.CharField(default='', max_length=20)),
                ('owner', models.CharField(default='', max_length=100)),
                ('dt_opened', models.DateField(auto_now_add=True)),
                ('interest_rt', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default='', max_length=400)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('balance', models.IntegerField(default='0')),
                ('prevbalance', models.IntegerField(default='0')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banking.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Forecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=40)),
                ('howoften', models.CharField(default='', max_length=200)),
                ('start_dt', models.DateField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cashforecast', to='banking.Accounts')),
            ],
        ),
    ]
