# Generated by Django 3.0.3 on 2020-02-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='hello',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='interest_rt',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
