# Generated by Django 3.0.3 on 2020-02-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_auto_20200219_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='balance',
            field=models.IntegerField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='transactions',
            name='prevbalance',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
