# Generated by Django 3.0.3 on 2020-02-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20200219_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default='0', max_length=400),
        ),
    ]
