# Generated by Django 3.0.3 on 2020-02-23 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20200223_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='cash_forecast',
            name='Entry_Type',
            field=models.CharField(choices=[('I', 'Income'), ('B', 'Bill')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
