# Generated by Django 3.0.3 on 2020-02-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_cash_forecast_entry_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ('-id',)},
        ),
    ]
