# Generated by Django 3.0.3 on 2020-02-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20200223_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='balance',
            field=models.IntegerField(default='0'),
        ),
    ]
