# Generated by Django 3.0.3 on 2020-02-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_auto_20200219_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='beg_bal',
            field=models.IntegerField(default='0', max_length=100),
        ),
    ]
