# Generated by Django 3.0.3 on 2020-02-21 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_cashforecast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cashforecast',
            new_name='Cash_Forecast',
        ),
    ]
